#!/system/bin/sh

# Block unwanted wakelocks
WAKELOCKS="12860000.decon_f;ssp_comm_wake_lock;ssp_wake_lock;tsp_wakelock;umts_ipc0;umts_ipc1"
echo $WAKELOCKS > /sys/class/misc/boeffla_wakelock_blocker/wakelock_blocker
