#!/sbin/sh

. "$env";

cd "${tmp}/rz_system" && [ "$(ls)" ] || exit 0;

chmod -R 0755 .;

## libsecure_storage patch ##
print "Setting libsecure_storage permissions...";

# Delete wrongly replaced libsecure_storage paths
rm -rf /system/vendor/lib/libsecure_storage.so;
rm -rf /system/vendor/lib64/libsecure_storage.so;

# Change permissions
chmod 0644 ./lib/libsecure_storage.so;
chmod 0644 ./lib64/libsecure_storage.so;

## Vendor fimc binaries patch ##
print "Setting fimc binaries permissions...";
find ./vendor/firmware -name '*.bin' -exec chmod 0644 {} \;

print "Copying patched files into system path";
cp -rf ${tmp}/rz_system /system/rz_system;
chmod 0755 /system/rz_system;

# Remove RMM lock (credits: @corsicanu)
print "Removing RMM lock... (credits: corsicanu@XDA)";
sed -i 's/vaultkeeper\.feature\=1/vaultkeeper\.feature\=0/' /system/build.prop;
rm -f /system/lib/libvk*;
rm -f /system/lib64/libvk*;
rm -rf /system/priv-app/Rlc;
rm -rf /system/priv-app/KnoxGuard;

# Remove RMM lock (credits: @corsicanu)
print "Removing RMM lock... (credits: corsicanu@XDA)";
sed -i 's/vaultkeeper\.feature\=1/vaultkeeper\.feature\=0/' /system/build.prop;
rm -f /system/lib/libvk*;
rm -f /system/lib64/libvk*;
rm -rf /system/priv-app/Rlc;
rm -rf /system/priv-app/KnoxGuard;

#### Originally written by @djb77 ####
# Remove unwanted file from /system/app/mcRegistry
rm -f /system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin;

# Remove Security Log Agent
rm -rf /system/app/SecurityLogAgent;

exit 0;
